// src/models/CreditCard.ts

import mongoose, { Schema } from "mongoose";
import { CreditCardInterface } from "../interfaces/CreditCard";

// Create the CreditCard schema
const CreditCardSchema: Schema = new Schema(
	{
		// _id is auto-generated by MongoDB, no need to define it
		cardNumber: { type: String, required: true }, // Card number
		expiryDate: { type: String, required: true }, // Expiry date of the card
		holderName: { type: String, required: true }, // Name of the cardholder
	},
	{ timestamps: true },
); // Automatically manage createdAt and updatedAt

// Create the CreditCard model
const CreditCard = mongoose.model<CreditCardInterface>(
	"CreditCard",
	CreditCardSchema,
);

export default CreditCard;
