import mongoose, { Schema } from "mongoose";
import { ItemInterface } from "../interfaces/Item";
import { ItemCondition } from "../enums/itemEnums";
import { ItemStatus } from "../enums/statusEnums";
import { AuthenticationStatus, ReturnStatus } from "../enums/flowEnums";
import OutfitItem from "./OutfitItem";
import OrderItem from "./OrderItem";

// Create the Item schema
const ItemSchema: Schema = new Schema(
	{
		// _id is auto-generated by MongoDB, no need to define it
		basePrice: { type: String, required: true },
		//imageId: { type: Schema.Types.ObjectId, ref: "Image", required: true }, // Foreign key reference to Image
		condition: {
			type: String,
			enum: Object.values(ItemCondition),
			required: true,
		}, // Enum for condition
		uploadedAt: { type: Date, required: true },
		saleRate: { type: String, required: true },
		itemStatus: {
			type: String,
			enum: Object.values(ItemStatus),
			required: true,
		}, // Enum for status
		color: { type: String, required: true },
		size: { type: String, required: true },
		itemName: { type: String, required: true },
		itemModel: { type: String, required: false }, // Model name (e.g., "Brick Cassette small intrecciato leather shoulder bag")
		year: { type: String, required: false }, // Year of the item (e.g., "2024")
		quantity: { type: String, required: true },
		brandName: { type: String, required: true },
		imageUrls: [{ type: String, required: true }], // List of URLs of the item's images
		receiptPhotoUrls: [{ type: String, required: false }],
		priceEstimatorUrls: [{ type: String, required: false }],
		quoteUrls: [{ type: String, required: false }],
		approved: { type: Boolean, default: false },
		approvedNextDrop: { type: Boolean, default: false },
		orderId: { type: Schema.Types.ObjectId, ref: "Order", required: false },
		authNeeded: { type: Boolean, default: false },
		cleaningNeeded: { type: Boolean, default: false },
		listingPrice: { type: String, required: true },
		photographed: { type: Boolean, default: false },
		authenticationStatus: {
			type: String,
			enum: Object.values(AuthenticationStatus),
			required: false,
		},
		authenticatedAt: { type: Date, required: false },
		returnDate: { type: Date, required: false },
		returnStatus: {
			type: String,
			enum: Object.values(ReturnStatus),
			required: false,
		},
		seller_id: {
			type: Schema.Types.ObjectId,
			ref: "User",
			index: true,
		}, // Optional: reference to seller userId
		category_id: {
			type: Schema.Types.ObjectId,
			ref: "Category",
			required: true,
			index: true,
		},
		sub_category_id: {
			type: Schema.Types.ObjectId,
			ref: "SubCategory",
			index: true,
		}, // Optional
		drop_id: {
			type: Schema.Types.ObjectId,
			ref: "Drop",
			index: true,
		}, // Optional: Reference to Drop
	},
	{ timestamps: true },
); // Automatically manage createdAt and updatedAt

// Cascade delete OrderItems and OutfitItems when an Item is deleted
ItemSchema.pre("findOneAndDelete", async function (next) {
	const doc = await this.model.findOne(this.getFilter());
	if (doc) {
		await OutfitItem.deleteMany({ item_id: doc._id });
		await OrderItem.deleteMany({ item_id: doc._id });
	}
	next();
});

// Create the Item model
const Item = mongoose.model<ItemInterface>("Item", ItemSchema);

export default Item;
